<a href="https://colab.research.google.com/github/sakurasakura1996/Pytorch-start-learning/blob/master/Dive_into_DL_Pytorch_2_2%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
ls

drive/  sample_data/


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
os.chdir("./drive")

In [0]:
os.chdir("./My Drive/pytorch_learning")

In [0]:
# 数据操作 torch.Tensor 是存储和变换数据的主要工具，用过numpy的话会觉的Tensor和numpy中的多维数组很相似。然而，Tensor提供了GPU运算和自动梯度
# 等更多功能。所以Tensor更适合深度学习 "tensor"这个单词一般翻译为张量，张量可以看成多维数组，标量是0维张量，向量是一维张量，矩阵是二维张量
import torch

In [0]:
# 2.2.1 创建Tensor
x = torch.empty(5, 3)
print(x)
# 这里创建的是未初始化的tensor

tensor([[5.2157e-38, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [3.3356e-09, 6.6474e+22, 8.3193e+20],
        [2.1005e+20, 1.6822e-04, 8.5381e-07],
        [2.6687e-09, 3.2917e-09, 5.0948e-14]])


In [0]:
x = torch.rand(5,3)
print(x)
# 创建了随机初始化的tensor

tensor([[0.7065, 0.8768, 0.6812],
        [0.6976, 0.3529, 0.4352],
        [0.3454, 0.3821, 0.0897],
        [0.9557, 0.7654, 0.7216],
        [0.6035, 0.3757, 0.8977]])


In [0]:
# 创建long型全0的tensor，注意类型的定义,用dtype
x = torch.zeros(5,3,dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
# 还可以直接根据数据来创建
x =torch.tensor([4, 3])
print(x)
print(type(x))

tensor([4, 3])
<class 'torch.Tensor'>


In [0]:
# 还可以通过现有的Tensor创建，此方法会默认重用输入 Tensor的一些属性，例如数据类型，除非自定义数据类型
x = x.new_ones(4, 4)  # 返回的tensor默认具有相同torch.dtype 和 torch.device（cpu or gpu)
# 上面的意思就是新创建的tensor和已有的x tensor拥有相同的dtype和device 除非特殊声明，new_ones()中的size参数不能少
print(x)
print(x.dtype)

x = torch.rand_like(x, dtype=torch.float)   # 指定数据类型
print(x)
print(x.dtype)    # torch.float默认是 float32

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.int64
tensor([[0.7826, 0.0348, 0.4266, 0.4664],
        [0.4528, 0.8582, 0.5283, 0.2574],
        [0.8035, 0.4462, 0.6204, 0.5401],
        [0.8533, 0.5525, 0.7462, 0.3785]])
torch.float32


In [0]:
# 可以通过shape 或者 size() 来获取tensor 的形状
print(x.size())
print(x.shape)
# 注意，返回的torch.Size 其实就是一个 tuple， 支持所有tuple的操作 元组
print(type(x.shape))

torch.Size([4, 4])
torch.Size([4, 4])
<class 'torch.Size'>


In [0]:
# 还有很多种创建tensor的方式，这里再列举 均匀和标准分布的例子，
x = torch.rand(5,3)   # 随机初始化 就是均匀分布
print(x)
x = torch.randn(5,3)   # 标准正态分布
print(x)

# x = torch.normal(0,0.5)   # 正态分布，参数中分别是均值mean和标准差 std 这里写的还不多，normal() 要求mean 和 std必须是Tensor 和 float中的
# 一种，两两组合就有四种情况都可以定义出来，并且后需要定义参数 torch.Generator  和 Tensor out两个参数，
x = torch.normal(mean=0.5, std=torch.arange(1.0,6))   # 离散正态分布 返回一个张量，包含了从指定均值means和标准差std的离散正态分布中抽取的一组随机数。
# 标准差std是一个张量，包含每个输出元素相关的正态分布标准差。
print(x)   # 这里要注意 torch.arange(1,6)会返回一个longType的形式而报错，

tensor([[0.7441, 0.1626, 0.3877],
        [0.0969, 0.4559, 0.3553],
        [0.0619, 0.2029, 0.2093],
        [0.1654, 0.8216, 0.2568],
        [0.1894, 0.5788, 0.5157]])
tensor([[ 0.7054,  0.7837,  0.3517],
        [-0.4680, -0.9191,  0.3504],
        [-3.2290, -0.5712, -0.5749],
        [-0.1826,  0.2466,  1.7595],
        [-1.1130, -1.6568, -1.3066]])
tensor([ 0.2486,  2.4009, -3.9355,  0.2599, -0.7448])


In [0]:
# 创建tensor时都可以指定数据类型和存放device（cpu or gpu)
x = torch.randn(5,3,dtype=torch.float16,device='cuda')
print(x)
print(x.device)

y = torch.randn(5,3)
print(y.device)

tensor([[-0.1692, -1.4209,  1.4619],
        [-0.1663,  0.1781,  1.1670],
        [-0.1111, -0.0269,  0.0755],
        [ 0.8491, -0.0025,  0.0340],
        [ 0.1139,  0.5752, -0.1713]], device='cuda:0', dtype=torch.float16)
cuda:0
cpu


In [0]:
# 2.2.2 操作
# 介绍tensor各种操作

In [0]:
# 算术操作   pytorch中，同一种操作可能有很多形式
# 加法  
# 形式一
x = torch.rand(5,3)
print(x+y)
# 形式二
print(torch.add(x,y))
# 形式三 指定输出
ans = torch.rand(5,3)
torch.add(x,y,out=ans)
print(ans)
# 形式四 inplace 将一个加数加到另一个加数上，相当于  a=a+b
y.add_(x)    # 相当于y = x+y
print(y)

tensor([[-0.0805,  1.5663,  0.5424],
        [ 0.6752,  3.3876, -0.8825],
        [ 1.4824,  1.2662, -0.0783],
        [ 0.1228, -0.9484,  0.4187],
        [-0.7978,  0.8151,  0.6267]])
tensor([[-0.0805,  1.5663,  0.5424],
        [ 0.6752,  3.3876, -0.8825],
        [ 1.4824,  1.2662, -0.0783],
        [ 0.1228, -0.9484,  0.4187],
        [-0.7978,  0.8151,  0.6267]])
tensor([[-0.0805,  1.5663,  0.5424],
        [ 0.6752,  3.3876, -0.8825],
        [ 1.4824,  1.2662, -0.0783],
        [ 0.1228, -0.9484,  0.4187],
        [-0.7978,  0.8151,  0.6267]])
tensor([[-0.0805,  1.5663,  0.5424],
        [ 0.6752,  3.3876, -0.8825],
        [ 1.4824,  1.2662, -0.0783],
        [ 0.1228, -0.9484,  0.4187],
        [-0.7978,  0.8151,  0.6267]])


In [0]:
# 索引  我们可以使用类似numpy的索引操作来访问tensor中的部分，需注意，索引出来的结果与原数据 共享内存，一个改了另一个也就改了
y = x[0, :]
print(y)
print(x[0, :])
y += 1    # 这里的加1是张量加1，和numpy是一样的，广播机制
print(y)
print(x[0, :])


tensor([1.4240, 1.2552, 1.5928])
tensor([1.4240, 1.2552, 1.5928])
tensor([2.4240, 2.2552, 2.5928])
tensor([2.4240, 2.2552, 2.5928])


In [0]:
# 除了常用的索引选择数据之外，pytorch还提供了一些高级的选择函数
# index_select(input, dim, index)  在指定维度dim上选取，比如选取某些行，某些列
# y = torch.index_select(x, 1, 2)    这里报错了，index参数需要输入 tensor 
print(x)
y = torch.index_select(x,1,torch.tensor([1]))  
print(y)

# masked_select(input, mask)  该函数找出input中关于mask选择条件的元素，并返回一维tensor
x = torch.randn(4,3)
print(x)
mask = (x > 0)    # 原先写成 mask = torch.ByteTensor(x>0)已经不对了
print(mask)

ans = torch.masked_select(x,mask)
print(ans)

tensor([[ 1.1511,  0.7252, -0.7877],
        [-0.4114,  0.3004, -1.5361],
        [ 0.3173,  0.1144, -1.5722],
        [-0.3602, -1.1143,  0.2565]])
tensor([[ 0.7252],
        [ 0.3004],
        [ 0.1144],
        [-1.1143]])
tensor([[ 1.4449, -1.7046, -0.6048],
        [ 0.3801,  0.9479, -0.8370],
        [ 0.5389,  1.0403, -0.6453],
        [ 2.2299, -0.1705,  1.4203]])
tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True, False,  True]])
tensor([1.4449, 0.3801, 0.9479, 0.5389, 1.0403, 2.2299, 1.4203])


In [0]:
# 改变形状  用view()来改变tensor的形状
y = x.view(12)
z = x.view(-1,4)   # -1可以根据另外一个维度算出来，相当于由后面的值来确定他
print(x.size(), y.size(), z.size())
# 注意 view()返回的新的tensor还是和上面的索引取数是一样的，还是共享内存，通过任何一个tensor改变值，最后都会改变，view顾名思义就是改变了原有
# tensor的观察角度 如果我们像返回一个 真正的新的副本即不共享内存，该怎么办。
# pytorch还提供了一个reshape()来改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用，建议先clone()创造一个副本，然后再使用view()
print(x)
x_cp = x.clone().view(12)
print(x_cp)
x_cp[2] = 0.3
print(x)
print(x_cp)
# 使用clone()还有一个好处，会被记录在计算图中，即梯度回传到副本时也会回传到源tensor。  这句话有待后面的了解

torch.Size([4, 3]) torch.Size([12]) torch.Size([3, 4])
tensor([[ 1.4449, -1.7046, -0.6048],
        [ 0.3801,  0.9479, -0.8370],
        [ 0.5389,  1.0403, -0.6453],
        [ 2.2299, -0.1705,  1.4203]])
tensor([ 1.4449, -1.7046, -0.6048,  0.3801,  0.9479, -0.8370,  0.5389,  1.0403,
        -0.6453,  2.2299, -0.1705,  1.4203])
tensor([[ 1.4449, -1.7046, -0.6048],
        [ 0.3801,  0.9479, -0.8370],
        [ 0.5389,  1.0403, -0.6453],
        [ 2.2299, -0.1705,  1.4203]])
tensor([ 1.4449, -1.7046,  0.3000,  0.3801,  0.9479, -0.8370,  0.5389,  1.0403,
        -0.6453,  2.2299, -0.1705,  1.4203])


In [0]:
# 另外一个常用函数就是item()，它可以将一个标量tensor 转换成一个python number
x = torch.randn(1)
print(x)
print(x.item())
# 标量tensor也就是包含一个元素的tensor

tensor([-2.5068])
-2.5067639350891113


In [0]:
# 线性代数
# pytorch还支持一些线性函数，这里提一下。
# t->转置    dot->内积  cross->外积   inverse->求逆矩阵   trace->对角线元素之和（矩阵的迹)
#  diag->对角线元素   triu/tril->矩阵的上三角/下三角   等等很多，如果用得到可以自定查看文档
x = torch.randn(4,3)
print(x)
print(torch.t(x))
# print(torch.inverse(x))    # 逆矩阵必须是n*n的
# print(torch.cross(x,torch.t(x)))   这里报错的原因是因为 内积外积都是针对向量的而不是二维或者更高维的
print(torch.mm(x,torch.t(x)))   # 矩阵乘法用 torch.mm（）

tensor([[-2.2794,  0.4233, -0.6875],
        [ 0.1768,  1.9702,  1.9058],
        [-0.0081, -0.3763,  1.9659],
        [ 2.0266, -0.5763, -1.1529]])
tensor([[-2.2794,  0.1768, -0.0081,  2.0266],
        [ 0.4233,  1.9702, -0.3763, -0.5763],
        [-0.6875,  1.9058,  1.9659, -1.1529]])
tensor([[ 5.8474, -0.8791, -1.4924, -4.0707],
        [-0.8791,  7.5450,  3.0037, -2.9742],
        [-1.4924,  3.0037,  4.0063, -2.0659],
        [-4.0707, -2.9742, -2.0659,  5.7682]])


In [0]:
# 2.2.3 广播机制
# 前面我们看到如何对两个形状相同的tensor元素做按元素运算。当对两个形状不同的tensor按元素运算时，可能会触发广播机制：先适当复制元素使
# 这两个tensor形状相同后再按元素运算。例如
import torch
x =  torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)
# 因为这两个tensor形状不一样，所以他们就都转换为3*2 形状的tensor，原来没有元素的地方就是直接复制元素就可以了

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [0]:
# 2.2.4 运算的内存开销
# 前面说了，索引、view是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用python自带的id函数：
# 如果两个实例的ID一致，那么他们所对应的内存地址相同；反之则不同
x = torch.tensor([1,2])
y = torch.tensor([4,5])
id_origin = id(y)
y = y+x
id_now = id(y)
print(id_origin, id_now)
# 结果是前后两个y并不一样啊，说明赋值之后又重开了新内存

139820827847848 139820827847632


In [0]:
# 如果我们想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作。下面我们把 x+y 的结果通过[:]写进y对应的内存中
x = torch.tensor([1,2])
y = torch.tensor([2,4])
id_before = id(y)
y[:] = y+x
print(id(y)==id_before)

True


In [0]:
# 我们还可以使用运算符全名函数中的out参数或者自加运算符+= （也就是add_()）达到上述效果，
x = torch.tensor([2,3])
y = torch.tensor([1,1])
z = torch.tensor([4,3])
id_y_before = id(y)
id_z_before = id(z)
torch.add(x,y,out=y)
z+=x   # 这个等于 z.add_(x)
print("y:"+str(id(y)==id_y_before))
print("z:"+str(id(z)==id_z_before))

y:True
z:True


In [0]:
# 2.2.5 tensor 和  numpy相互转换
# 我们很容易用  numpy()  和 from_numpy()将 tensor 和 numpy中的数字相互转换
# 但是需要注意一点：这两个函数所产生的tensor和 numpy中的数组共享相同的内存（所以转换很快)

# tensor转numpy  -->使用numpy() 将tensor转换成numpy数组
a = torch.ones(5)
b = a.numpy()
print(a,b)
a += 1
print(a,b)
b +=1
print(a,b)    #共享内存

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [0]:
# numpy数组转tensor   from_numpy() 将numpy数组转换为 tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

a +=1 
print(a,b)

b+=1
print(a,b)    # 共享内存


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [0]:
# 还有一个常用方法直接用 torch.tensor()将numpy数组转换成 tensor，需要注意的是该方法总是会进行数据拷贝，返回的tensor和原来数据不进行内存共享
c = torch.tensor(a)
a +=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [0]:
# 2.2.6 tensor on GPU
# 用方法to() 可以将 tensor 在CPU 和GPU 之间相互移动
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu",torch.double))   # to() 还可以同时改变数据类型   
  # 但是这里移动之后，z还是在GPU上面，必须再给他赋给某一个变量，这个变量才是在cpu的内存中了
  c = z.to("cpu",torch.double)
  print(c)
  print(z.device)
  print(z.to("cpu",torch.double).device)
  print(c.device)

tensor([3, 4], device='cuda:0')
tensor([3., 4.], dtype=torch.float64)
tensor([3., 4.], dtype=torch.float64)
cuda:0
cpu
cpu
